# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Set the theme/colors to use
palette = "tokyo-night"

# The actual prompt configuration
format = """
[](color1)\
$os\
$username\
$hostname\
[](fg:color1 bg:color2)\
$directory\
[](fg:color2 bg:color3)\
$git_branch\
$git_status\
[](fg:color3)
$character
"""

right_format = """
[](color6)\
$cmd_duration\
$time\
[](fg:color6)
"""

[os]
disabled = false
style = "fg:text3 bg:color1"

[os.symbols]
Windows = "󰍲"
Macos = "󰀵"
Linux = "󰌽"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Debian = "󰣚"
Fedora = "󰣛"
Manjaro = ""
Mint = "󰣭"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Ubuntu = "󰕈"

[username]
show_always = true
style_user = "fg:text3 bg:color1"
style_root = "bold fg:text3 bg:color1"
format = "[ $user ]($style)"

[hostname]
ssh_only = true
style = "fg:text3 bg:color1"
format = "[@ $hostname ]($style)"

[directory]
truncation_length = 3
truncation_symbol = ".../"
style = "fg:text1 bg:color2"
format = "[ $path ]($style)[$read_only]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"/mnt/truenas" = "TrueNAS"
"/mnt/sdc1" = "A1-2000"
"/mnt/sdb1" = "B1-2000"
"/mnt/sda1" = "B2-2000"
"/mnt/sdd1" = "B3-2000"
"/run/media/otavio/Otavio750" = "Otavio750"

[git_branch]
symbol = ""
style = "fg:text2 bg:color3"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bold fg:text2 bg:color3"
format = "[($all_status$ahead_behind )]($style)"

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "fg:text1 bg:color6"
format = "[$duration]($style)"

[time]
disabled = false
time_format = "%T"              # HH:MM:SS format
style = "fg:text1 bg:color6"
format = "[   $time ]($style)"

[character]
disabled = false
success_symbol = "[↪](bold fg:prompt1)"
error_symbol = "[↩](bold fg:prompt2)"
vimcmd_symbol = "[↞](bold fg:yellow)"
vimcmd_replace_one_symbol = "[↞](bold fg:yellow)"
vimcmd_replace_symbol = "[↞](bold fg:yellow)"
vimcmd_visual_symbol = "[↞](bold fg:yellow)"

# Color themes
[palettes.tokyo-night]
# Adapted from tokyo night preset
# https://starship.rs/presets/tokyo-night
prompt1 = "#a6e3a1"
prompt2 = "#f38ba8"
color1 = "#a3aed2"
color2 = "#769ff0"
color3 = "#1d2230"
color4 = "#"
color5 = "#"
color6 = "#394260"
text1 = "#e3e5e5"
text2 = "#769ff0"
text3 = "#090c0c"

[palettes.catppuccin_mocha]
# Adapted from catppuccin_mocha preset
# https://starship.rs/presets/catppuccin-powerline
prompt1 = "#a6e3a1"
prompt2 = "#f38ba8"
color1 = "#313244"
color2 = "#b4befe"
color3 = "#8839ef"
color4 = "#"
color5 = "#"
color6 = "#f9e2af"
text1 = "#1e1e2e"
text2 = "#1e1e2e"
text3 = "#cdd6f4"
