# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Set the theme/colors to use
palette = 'catppuccin_mocha'

# The actual prompt configuration
format = """
[](surface0)\
$os\
$username\
$hostname\
[](fg:surface0 bg:lavender)\
$directory\
[](fg:lavender bg:purple)\
$git_branch\
$git_status\
[](fg:purple)
$character
"""

right_format = """
[](yellow)\
$cmd_duration\
$time\
[](fg:yellow)
"""

[os]
disabled = false
style = 'fg:text bg:surface0'

[os.symbols]
Windows = '󰍲'
Macos = ''
Linux = '󰌽'
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
Debian = '󰣚'
Fedora = '󰣛'
Manjaro = ''
Mint = '󰣭'
Redhat = '󱄛'
RedHatEnterprise = '󱄛'
Ubuntu = '󰕈'

[username]
show_always = true
style_user = 'fg:text bg:surface0'
style_root = 'bold fg:text bg:surface0'
format = '[ $user ]($style)'

[hostname]
ssh_only = true
style = 'fg:text bg:surface0'
format = '[@ $hostname ]($style)'

[directory]
style = 'fg:base bg:lavender'
format = '[ $path ]($style)[$read_only]($style)'
truncation_length = 4
truncation_symbol = '.../'

[directory.substitutions]
'/mnt/truenas' = 'TrueNAS'
'/mnt/sdc1' = 'A1-2000'
'/mnt/sdb1' = 'B1-2000'
'/mnt/sda1' = 'B2-2000'
'/mnt/sdd1' = 'B3-2000'
'/run/media/otavio/Otavio750' = 'Otavio750'

[git_branch]
style = 'fg:base bg:purple'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'bold fg:base bg:purple'
format = '[($all_status$ahead_behind )]($style)'

[cmd_duration]
min_time = 1000
style = 'fg:mantle bg:yellow'
format = '[$duration]($style)'

[time]
disabled = false
time_format = '%T'
style = 'fg:base bg:yellow'
format = '[   $time ]($style)'

[character]
# Replace the '❯' symbol in the prompt with '➜'
disabled = false
success_symbol = '[↪](bold fg:green)'
error_symbol = '[↩](bold fg:red)'
vimcmd_symbol = '[↞](bold fg:creen)'
vimcmd_replace_one_symbol = '[↞](bold fg:purple)'
vimcmd_replace_symbol = '[↞](bold fg:purple)'
vimcmd_visual_symbol = '[↞](bold fg:lavender)'

# Color themes
[palettes.catppuccin_latte]
rosewater = '#dc8a78'
flamingo = '#dd7878'
pink = '#ea76cb'
mauve = '#8839ef'
red = '#d20f39'
maroon = '#e64553'
peach = '#fe640b'
yellow = '#df8e1d'
green = '#40a02b'
teal = '#179299'
sky = '#04a5e5'
sapphire = '#209fb5'
blue = '#1e66f5'
lavender = '#7287fd'
text = '#4c4f69'
subtext1 = '#5c5f77'
subtext0 = '#6c6f85'
overlay2 = '#7c7f93'
overlay1 = '#8c8fa1'
overlay0 = '#9ca0b0'
surface2 = '#acb0be'
surface1 = '#bcc0cc'
surface0 = '#ccd0da'
base = '#eff1f5'
mantle = '#e6e9ef'
crust = '#dce0e8'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[palettes.catppuccin_macchiato]
rosewater = '#f4dbd6'
flamingo = '#f0c6c6'
pink = '#f5bde6'
mauve = '#c6a0f6'
red = '#ed8796'
maroon = '#ee99a0'
peach = '#f5a97f'
yellow = '#eed49f'
green = '#a6da95'
teal = '#8bd5ca'
sky = '#91d7e3'
sapphire = '#7dc4e4'
blue = '#8aadf4'
lavender = '#b7bdf8'
text = '#cad3f5'
subtext1 = '#b8c0e0'
subtext0 = '#a5adcb'
overlay2 = '#939ab7'
overlay1 = '#8087a2'
overlay0 = '#6e738d'
surface2 = '#5b6078'
surface1 = '#494d64'
surface0 = '#363a4f'
base = '#24273a'
mantle = '#1e2030'
crust = '#181926'
